#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# start picom, which ever fork has rounded corners and blur.
picom --config /home/justenb/.config/picom/picom.conf --experimental-backends  -b

bspc monitor eDP-1  -d I II III 
bspc monitor DP-1-2 -d IV V

bspc config top_padding        30 
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config focused_border_color "#9370DB"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc rule -a Screenkey manage=off

# Plasma rules
bspc rule -a plasmashell state=floating border=off sticky=off center=off
bspc rule -a krunner state=floating border=off
bspc rule -a systemsettings state=floating 
bspc rule -a plasma-desktop state=floating border=off

